### ISSUE TITLE
Tide cannot merge PRs

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/testgrid#22]
Like #21 

```yaml
{
 insertId: "18yp9g6g35eykho"  
 jsonPayload: {
  base-sha: "40ea4b98d6e70a573c66b44534d4b056bead998f"   
  branch: "master"   
  component: "tide"   
  controller: "sync"   
  error: "failed merging [21]: [PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? Required status check "cla/google" is expected.]"   
  file: "prow/tide/tide.go:356"   
  func: "k8s.io/test-infra/prow/tide.(*Controller).Sync.func2"   
  level: "error"   
  msg: "Error syncing subpool."   
  org: "GoogleCloudPlatform"   
  repo: "testgrid"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/tide"  
 receiveTimestamp: "2019-09-28T00:07:39.681698538Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-09-28T00:07:38Z"  
}
```

/assign @michelle192837 @fejta 
/kind oncall-hotlist
