### ISSUE TITLE
OWNERS file asks to create non-existent testgrid label

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/testgrid#31]
```yaml
{
 insertId: "nljb5cg3r3hu17"  
 jsonPayload: {
  author: "chases2"   
  component: "hook"   
  event-GUID: "a4d8c620-eade-11e9-9cd9-41ac81003eb0"   
  event-type: "pull_request"   
  file: "prow/plugins/owners-label/owners-label.go:119"   
  func: "k8s.io/test-infra/prow/plugins/owners-label.handle"   
  level: "warning"   
  msg: "Unable to add nonexistent labels: ["area/testgrid"]"   
  org: "GoogleCloudPlatform"   
  plugin: "owners-label"   
  pr: 30   
  repo: "testgrid"   
  url: "https://github.com/GoogleCloudPlatform/testgrid/pull/30"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/hook"  
 receiveTimestamp: "2019-10-09T21:49:23.652030032Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T21:49:20Z"  
}
```

/assign @chases2 
/kind oncall-hotlist

https://github.com/GoogleCloudPlatform/testgrid/blob/1267574fd31181b3ff3448231e01bac5fb409c93/OWNERS#L15-L16
